### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by achenglike** [YummyLau/Anchors#30]
AnchorsRuntime#runBlockTask 存在多线程操作问题，tryRunBlockRunnable 主线程操作 addRunTasks 在主线程和工作现场都会操作，导致多线程问题。

`Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList.sort(ArrayList.java:1472)
	at java.util.Collections.sort(Collections.java:201)
	at com.effective.android.anchors.AnchorsRuntime.tryRunBlockRunnable$anchors_release(AnchorsRuntime.kt:3)
	at com.effective.android.anchors.AnchorsManager.start(AnchorsManager.kt:17)`

**Comment by YummyLau** [comment]
@achenglike 目前有手动添加addRunTasks么？ 还是执行框架依赖图。

**Comment by achenglike** [comment]
> @achenglike 目前有手动添加addRunTasks么？ 还是执行框架依赖图。

没有主动调用。各个task做完dependOn排序后直接把UI早的task交给AnchrosManager进行了start

`//java 代码
AnchorsManager.getInstance().debuggable(true) 
        .addAnchors(anchorYouNeed)          //传递任务id设置锚点任务
        .start(dependencyGraphHead);        //传入依赖图头部`

此种方式

**Comment by YummyLau** [comment]
@achenglike 嗯嗯收到。这个问题会尽快处理。

**Comment by YummyLau** [comment]
v1.1.4，使用jitPack依赖
