### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by billdizl** [YummyLau/Anchors#37]
java.lang.IllegalArgumentException
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6784)
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7892)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
//use sdk version: com.github.YummyLau:Anchors:v1.1.4

**Comment by LinYYY** [comment]
感谢反馈，v1.1.8已修复
