### ISSUE TITLE
java.lang.RuntimeException: can no run task task-lock again!

### ISSUE THREAD

**Issue by darrenjh** [YummyLau/Anchors#38]
implementation 'com.effective.android:anchors:1.1.3'
这个问题是什么原因？
java.lang.RuntimeException: can no run task task-lock again!
	at com.effective.android.anchors.task.Task.start(SourceFile:6)
	at com.effective.android.anchors.task.Task.dependTaskFinish(SourceFile:5)
	at com.effective.android.anchors.task.Task.notifyBehindTasks(SourceFile:7)
	at com.effective.android.anchors.task.Task.run(SourceFile:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8288)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by LinYYY** [comment]
task-lock这个task启动了两次 检查下任务链
