### ISSUE TITLE
反馈一个问题，从1.1.4升级到1.1.6，在OPPO R9s上出现崩溃。

### ISSUE THREAD

**Issue by allentsui** [YummyLau/Anchors#39]
机器： OPPO R9s，Android 6

 Caused by: java.lang.UnsupportedOperationException
        at java.util.concurrent.CopyOnWriteArrayList$CowIterator.set(CopyOnWriteArrayList.java:748)
        at java.util.Collections.sort(Collections.java:1909)
        at com.effective.android.anchors.task.Task.notifyBehindTasks(Task.kt:235)
        at com.effective.android.anchors.task.Task.run(Task.kt:73)
        at com.effective.android.anchors.AnchorsRuntime.tryRunBlockTask$anchors_release(AnchorsRuntime.kt:115)
        at com.effective.android.anchors.AnchorsManager.start(AnchorsManager.kt:111)
        at com.effective.android.anchors.AnchorsManagerKt.startUp(AnchorsManager.kt:279)
        at com.jelenew.app.startup.StartupHelper.startup(StartupHelper.kt:13)
        at com.jelenew.app.JelenewApplication.onCreate(JelenewApplication.kt:16)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4995)

**Comment by LinYYY** [comment]
感谢反馈，下个版本修复

**Comment by LinYYY** [comment]
@allentsui  v1.1.7版本已修复

> 机器： OPPO R9s，Android 6
> 
> Caused by: java.lang.UnsupportedOperationException at java.util.concurrent.CopyOnWriteArrayList$CowIterator.set(CopyOnWriteArrayList.java:748) at java.util.Collections.sort(Collections.java:1909) at com.effective.android.anchors.task.Task.notifyBehindTasks(Task.kt:235) at com.effective.android.anchors.task.Task.run(Task.kt:73) at com.effective.android.anchors.AnchorsRuntime.tryRunBlockTask$anchors_release(AnchorsRuntime.kt:115) at com.effective.android.anchors.AnchorsManager.start(AnchorsManager.kt:111) at com.effective.android.anchors.AnchorsManagerKt.startUp(AnchorsManager.kt:279) at com.jelenew.app.startup.StartupHelper.startup(StartupHelper.kt:13) at com.jelenew.app.JelenewApplication.onCreate(JelenewApplication.kt:16) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4995)
