### ISSUE TITLE
AnchorThreadPool.kt line 29 com.effective.android.anchors.AnchorThreadPool.<init>

### ISSUE THREAD

**Issue by billdizl** [YummyLau/Anchors#42]
设备
品牌：LGE
型号：Nexus 5X
屏幕方向： 纵向
可用 RAM： 3.2 GB
可用磁盘空间： 2.49 GB
操作系统
版本：Android 6.0.1
屏幕方向： 纵向
是否已取得 root 权限：是
崩溃
日期：2022年11月22日 01:41:02

SDK为最新的版本号
Fatal Exception: java.lang.RuntimeException: Unable to create application 包名.view.BaseApplication: java.lang.IllegalArgumentException
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4714)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Caused by java.lang.IllegalArgumentException:
       at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1278)
       at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1201)
       at com.effective.android.anchors.AnchorThreadPool.<init>(AnchorThreadPool.kt:29)
       at com.effective.android.anchors.AnchorsRuntime.<init>(AnchorsRuntime.kt:51)
       at com.effective.android.anchors.AnchorsManager.<init>(AnchorsManager.kt:28)
       at com.effective.android.anchors.AnchorsManager.<init>(AnchorsManager.kt:19)
       at com.effective.android.anchors.AnchorsManager$Companion.getInstance(AnchorsManager.kt:35)
       at com.effective.android.anchors.AnchorsManager$Companion.getInstance$default(AnchorsManager.kt:34)
       at com.effective.android.anchors.AnchorsManager.getInstance(AnchorsManager.kt)
       at 包名view.BaseApplication.onCreate(BaseApplication.java:173)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4711)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

代码:
                //延时加载
                AnchorsManager.getInstance()
                        .debuggable(BuildConfig.DEBUG)
                        //设置锚点
                        .addAnchor(InitCaocConfig.TASK_ID,
                                InitMNCrashMonitor.TASK_ID,
                                InitAppsFlyer.TASK_ID,
                                InitFrontBack.TASK_ID,
                                InitFaceBook.TASK_ID,
                                InitAdId.TASK_ID,
                                InitKlarna.TASK_ID,
                                InitToast.TASK_ID
                                , InitForterPay.TASK_ID,
                                InitSmartRefreshLayout.TASK_ID

                        )
                        .start(new Project.Builder("chicmeapp", new AppTaskSdkFactory())
                                .add(InitCaocConfig.TASK_ID)
                                .add(InitMNCrashMonitor.TASK_ID)
                                .add(InitAppsFlyer.TASK_ID)
                                .add(InitFrontBack.TASK_ID)
                                .add(InitFaceBook.TASK_ID)
                                .add(InitAdId.TASK_ID)
                                .add(InitKlarna.TASK_ID)
                                .add(InitToast.TASK_ID)
                                .add(InitForterPay.TASK_ID)
                                .add(InitSmartRefreshLayout.TASK_ID)
                                .build()
                        );

**Comment by LinYYY** [comment]
感谢反馈，v1.1.8已修复
